[tool.black]
line-length = 88
target-version = ["py310"]
skip-string-normalization = true

[tool.ruff]
line-length = 88
select = ["E", "F", "I"]  # Pyflakes, pycodestyle, isort
ignore = ["E501"]         # Allow long lines (optional)

[tool.mypy]
python_version = "3.10"
strict = true
ignore_missing_imports = true
